### ISSUE TITLE
Request to add FG color to HangarMap.txt

### ISSUE THREAD

**Issue by ual002** [JeremyAnsel/xwa_hooks#3]
Quoting you:

"; Must contain at least 4 object line.
; Format is : model index, position X, position Y, position Z, heading XY, heading Z
; Numbers can be in decimal or hexadecimal (0x) notation.
; When position Z is set to 0x7FFFFFFF, this means that the object stands at the ground."

Can we add something right after model index for FG color?

**Comment by JeremyAnsel** [comment]
I've added setting markings (FG color).

In HangarMap and FamHangarMap:
The format is : model index, position X, position Y, position Z, heading XY, heading Z.
or : model index, markings, position X, position Y, position Z, heading XY, heading Z.

In HangarObjects:
To set the shuttle markings, set "ShuttleMarkings = value". value is an integer. The default value is 0.

**Comment by ual002** [comment]
Awesome!
